[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.118.2"  # Usa una versión más reciente de Hugo

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false  # Desactivado si no necesitas Cypress
