backend:
  name: git-gateway
  branch: main # La rama de tu repositorio que se usará para las ediciones

media_folder: "static/images/uploads" # Carpeta donde se subirán las imágenes
public_folder: "/images/uploads"

collections:
  - name: "pages" # Nombre de la colección
    label: "Páginas"
    folder: "content" # Carpeta donde se guardarán los archivos .md
    create: true # Permite crear nuevos archivos
    slug: "{{slug}}" # Define el nombre de los archivos
    fields: # Los campos que se pueden editar desde el CMS
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
